algoritmo "Valor positivo"
// Função :  Dar resposta ao usuário se o número informado é positivo ou negativo
// Autor :  Gabriel Ripardo
// Data : 28/03/2016
// Seção de Declarações 
var
num1 : REAL

inicio
// Seção de Comandos 
 escreva("Digite o valor: ")
 leia(num1)
 
 se num1 > -1 entao
 escreva("O número",num1 ," é Positivo")
 senao
 escreva("O número",num' ," é Negativo")
 
 Fimse
fimalgoritmo
