algoritmo "Loja de tintas"

// Autor : Gabriel Ripardo de Sena
// Data : 31/03/2016
// Seção de Declarações

Var
qtd: inteiro
m: real
inicio
escreval("     <<<<<<<      LOJA DE TINTAS     >>>>>>")
escreva("            Digite o tamanho da área:  ")
leia(m)
qtd <- int (m/3/18)
      escreval ("A quantidade de latas a serem compradas serão: ",qtd)
      escreval ("O valor a ser pago por quantidades de latas será R$:",qtd*80)
Fimalgoritmo
