Algoritmo "M para Cm"
// Autor(a)    : Gabriel Ripardo de Sena
// Data atual  : 25/03/2016
Var
// Seção de Declarações das variáveis 
metros : REAL
resultado : REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Número a ser convertido: ")
leia(metros)

resultado <- metros*100

escreva( metros , " m ao ser convertido para centímetros é igual a",resultado ," cm")

Fimalgoritmo
