Algoritmo "Valor da área"
// Descrição   : O programa irá calcular a área de um círculo
// Autor(a)    : Gabriel Ripardo de Sena
// Data atual  : 25/03/2016
Var
// Seção de Declarações das variáveis 
raio :  REAL
resultado : REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("O raio do círculo equivale à: ")
leia(raio)

resultado <- 3.1415 * (raio * raio)
escreva("A área do círculo equivale à: ", resultado)

Fimalgoritmo
