Algoritmo "Área do quadrado"
// Descrição   : O programa irá calcular a área do quadrado
// Autor(a)    : Gabriel Ripardo de Sena
// Data atual  : 25/03/2016
Var
// Seção de Declarações das variáveis 
lado : REAL
resultado : REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a área do quadrado a ser calculado: ")
leia(lado)

resultado <- (lado * lado) * 2
escreva("A área do quadrado equivale à: ", resultado ," m²")

Fimalgoritmo
