algoritmo "Números primos 2.0"
// Função : O progrma irá mostra todos os números primos entre 1 e N, sendo N um
//          número inteiro fornecido pelo usuário.
// Autor : Gabriel Ripardo
// Data : 12/04/2016
// Seção de Declarações 
var
limt, cont : INTEIRO

inicio
// Seção de Comandos
escreva("Digite um número inteiro: ")
leia(limt)

repita
cont <- cont + 1
cont2 <- cont + 1
     se cont mod cont2 = 0

fimalgoritmo
