algoritmo "Números de 1 à 20"
// Função : Informar números de 1 a 20 de baixo do próximo e depois ao lado.
// Autor : Gabriel Ripardo de Sena
// Data : 06/04/2016
// Seção de Declarações 
var
num : INTEIRO
num1 : INTEIRO
inicio
// Seção de Comandos
num <- 0

    repita
    num <- num + 1
    escreval(num)
    ate num = 20

num1 <- 1
    enquanto num1 <= 20  faca
    escreva(num1)
    num1 <- num1 + 1
    fimenquanto
    
fimalgoritmo
